apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbveileder
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbveileder/veilarbveileder:{{version}}
  port: 8080
  webproxy: true
  secureLogs:
    enabled: true
  liveness:
    path: veilarbveileder/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbveileder/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbveileder/internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://veilarbveileder.prod-fss-pub.nais.io
    - https://veilarbveileder.nais.adeo.no
    - https://app.adeo.no/veilarbveileder
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/veilarbveileder/default
        mountPath: /var/run/secrets/nais.io/vault
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: paw-proxy
          namespace: paw
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
        - application: veilarbportefolje
          namespace: pto
          cluster: prod-fss
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
  envFrom:
    - configmap: pto-config
  env:
    - name: LDAP_BASEDN
      value: dc=adeo,dc=no
    - name: LDAP_USER_BASEDN
      value: ou=NAV,ou=BusinessUnits,dc=adeo,dc=no
    - name: LDAP_SERVICEUSER_BASEDN
      value: ou=ServiceAccounts,dc=adeo,dc=no
    - name: LDAP_URL
      value: ldaps://ldapgw.adeo.no
    - name: LDAP_DOMAIN
      value: ADEO.NO
    - name: ABAC_MODIA_URL
      value: https://abac-modia.intern.nav.no/application/asm-pdp/authorize
