apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbveileder
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbveileder/veilarbveileder:{{version}}
  port: 8080
  webproxy: true
  secureLogs:
    enabled: true
  liveness:
    path: veilarbveileder/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbveileder/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbveileder/internal/prometheus
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://veilarbveileder.dev-fss-pub.nais.io
    - https://veilarbveileder.dev.intern.nav.no
    - https://veilarbveileder-q1.nais.preprod.local
    - https://app-q1.dev.adeo.no/veilarbveileder
    - https://app.dev.adeo.no/veilarbveileder
    - https://app-q1.adeo.no/veilarbveileder
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/veilarbveileder/q1
        mountPath: /var/run/secrets/nais.io/vault
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: paw-proxy
          namespace: paw
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: dev-gcp
        - application: veilarbfilter
          namespace: pto
          cluster: dev-fss
        - application: veilarbportefolje
          namespace: pto
          cluster: dev-fss
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: dev-gcp
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: dev-fss
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
  envFrom:
    - configmap: pto-config
  env:
    - name: LDAP_BASEDN
      value: dc=preprod,dc=local
    - name: LDAP_USER_BASEDN
      value: ou=NAV,ou=BusinessUnits,dc=preprod,dc=local
    - name: LDAP_SERVICEUSER_BASEDN
      value: ou=ServiceAccounts,dc=preprod,dc=local
    - name: LDAP_URL
      value: ldaps://ldapgw.preprod.local
    - name: LDAP_DOMAIN
      value: PREPROD.LOCAL
    - name: POAO_TILGANG_URL
      value: https://poao-tilgang.dev.intern.nav.no
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
