apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbveileder
  namespace: default
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbveileder/veilarbveileder:{{version}}
  port: 8080
  liveness:
    path: veilarbveileder/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbveileder/internal/selftest
    initialDelay: 20
  prometheus:
    enabled: true
    path: veilarbveileder/internal/metrics
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://veilarbveileder.nais.adeo.no
    - https://app.adeo.no/veilarbveileder
  vault:
    enabled: true
  envFrom:
    - configmap: pto-config
