apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbveileder
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbveileder/veilarbveileder:{{version}}
  port: 8080
  webproxy: true
  secureLogs:
    enabled: true
  liveness:
    path: veilarbveileder/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbveileder/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbveileder/internal/prometheus
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://veilarbveileder-q1.nais.preprod.local
    - https://app-q1.dev.adeo.no/veilarbveileder
    - https://app.dev.adeo.no/veilarbveileder
    - https://app-q1.adeo.no/veilarbveileder
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/veilarbveileder/q1
        mountPath: /var/run/secrets/nais.io/vault
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: paw-proxy
          namespace: paw
  envFrom:
    - configmap: pto-config
  env:
    - name: LDAP_BASEDN
      value: dc=preprod,dc=local
    - name: LDAP_USER_BASEDN
      value: ou=NAV,ou=BusinessUnits,dc=preprod,dc=local
    - name: LDAP_SERVICEUSER_BASEDN
      value: ou=ServiceAccounts,dc=preprod,dc=local
    - name: LDAP_URL
      value: ldaps://ldapgw.preprod.local
    - name: LDAP_DOMAIN
      value: PREPROD.LOCAL
    - name: ABAC_MODIA_URL
      value: https://abac-modia-q1.dev.intern.nav.no/application/asm-pdp/authorize
