apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbveileder
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  secureLogs:
    enabled: true
  liveness:
    path: veilarbveileder/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbveileder/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbveileder/internal/prometheus
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://veilarbveileder-gcp.intern.dev.nav.no
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: dev-gcp
        - application: veilarbfilter
          namespace: obo
          cluster: dev-gcp
        - application: veilarbportefolje
          namespace: obo
          cluster: dev-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: dev-gcp
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: dev-fss
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: dev-gcp
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
        - application: arbeidssokerregistrering-for-veileder
          namespace: paw
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
        - application: norg2
          namespace: org
      external:
        - host: axsys.dev-fss-pub.nais.io
  env:
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: NORG2_URL
      value: http://norg2.org/norg2
    - name: AXSYS_URL
      value: https://axsys.dev-fss-pub.nais.io
