apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbveileder
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  liveness:
    path: veilarbveileder/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbveileder/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbveileder/internal/prometheus
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 200m
      memory: 768Mi #https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  ingresses:
    - https://veilarbveileder-gcp.intern.nav.no
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
        - application: veilarbfilter
          namespace: obo
          cluster: prod-gcp
        - application: veilarbportefolje
          namespace: obo
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: prod-gcp
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: prod-fss
        - application: veilarbvedtaksstotte
          namespace: obo
          cluster: prod-gcp
        - application: arbeidssokerregistrering-for-veileder
          namespace: paw
          cluster: prod-gcp
        - application: inngar
          namespace: dab
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
        - application: norg2
          namespace: org
        - application: nom-api
          namespace: nom
      external:
        - host: axsys.prod-fss-pub.nais.io
        - host: team-obo-unleash-api.nav.cloud.nais.io
  env:
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: NORG2_URL
      value: http://norg2.org/norg2
    - name: AXSYS_URL
      value: https://axsys.prod-fss-pub.nais.io
    - name: MICROSOFT_GRAPH_URI
      value: https://graph.microsoft.com/v1.0
    - name: MICROSOFT_GRAPH_SCOPE
      value: https://graph.microsoft.com/.default
    - name: NOM_API_URL
      value: http://nom-api.nom
    - name: NOM_API_SCOPE
      value: api://prod-gcp.nom.nom-api/.default
  envFrom:
    - secret: veilarbveileder-unleash-api-token
