apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: veilarbveileder
  namespace: obo
  labels:
    team: obo
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: obo
  secretName: veilarbveileder-unleash-api-token
  environment: development
