name: Deploy til Dev
on:
  workflow_dispatch:
env:
  IMAGE_TAG: ${{ github.sha }}
  PRINT_PAYLOAD: true
permissions:
  packages: write 
  contents: write
jobs:
  test-build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build maven artifacts
        run: mvn -B package

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pto
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy application to dev
    needs: test-build-and-push
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/application/application-config-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
